# Generated by Django 2.2.28 on 2022-12-08 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20221207_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='unique review',
        ),
    ]
